# sources/distributed-fs/ceph-client/drivers/scsi/mpt3sas/mpi/mpi2_ioc.h

Purpose: defines the MPI v2 IOC, port, event, firmware transfer, power-management, MPI v2.6 IO Unit Control, and MCTP passthrough wire messages used by the `mpt3sas` driver. It is a protocol contract rather than executable code: structures and constants here must match firmware frame layouts byte-for-byte because request frames, reply frames, and event payloads are DMA-visible or copied directly from firmware replies.

Important APIs/types/functions: the initialization path uses `Mpi2IOCInitRequest_t`, `Mpi2IOCInitReply_t`, and `Mpi2IOCInitRDPQArrayEntry` to publish request/reply queue addresses, page size, MSI-X vector count, MPI/header versions, reply queue depths, RDPQ array mode, NVMe SGL format, and coredump enablement. Discovery and capability probing use `Mpi2IOCFactsRequest_t`/`Mpi2IOCFactsReply_t`, `Mpi2PortFactsRequest_t`/`Mpi2PortFactsReply_t`, and `Mpi2PortEnableRequest_t`/`Mpi2PortEnableReply_t`; the reply capability bits gate integrated RAID, diagnostic buffers, event replay, MSI-X index support, RDPQ array capability, NVMe protocol, coredump, SR-IOV, atomic requests, and MCTP passthrough. Event handling centers on `Mpi2EventNotificationRequest_t`, `Mpi2EventNotificationReply_t`, and `Mpi2EventAckRequest_t`; payload structs cover SAS discovery/topology/device status, IR volume and physical disk changes, log entries, temperature, power performance, active cable exceptions, SAS/PCIe topology, PCIe device status/enumeration/link counters, enclosure changes, host messages, quiesce, and SAS discovery errors. Firmware service structures include `Mpi2FWDownloadRequest`, `Mpi25FWDownloadRequest`, `Mpi2FWUploadRequest_t`, `Mpi25FWUploadRequest_t`, and their transaction-context SGEs/replies. Later sections define `Mpi2PwrMgmtControlRequest_t`, `Mpi26IoUnitControlRequest_t`, and `Mpi26MctpPassthroughRequest_t`.

Control flow: there is no runtime control flow in the header, but it drives the driver state machine. `mpt3sas_base.c` sends IOCFacts, stores the `Mpi2IOCFactsReply_t` in adapter state, allocates queues from the reported limits, then sends IOCInit and PortEnable. It posts event masks through `Mpi2EventNotificationRequest_t`, dispatches `Mpi2EventNotificationReply_t` payloads by `Event`, and issues `Mpi2EventAckRequest_t` when `AckRequired` is set. `mpt3sas_ctl.c` exposes many of these message formats to user ioctls and validates special cases such as MCTP capability, firmware upload/download, diagnostic operations, toolbox commands, and reset-producing IO Unit Control operations. `mpt3sas_scsih.c` consumes SAS and IR event data to add/remove devices, update RAID volume/physical disk state, and send remove-device IO Unit Control requests.

State and persistence: this header itself stores no state. Its fields represent persistent and transient controller state: IOCFacts persist in `struct MPT3SAS_ADAPTER` for feature gating; event masks and queue addresses remain active in firmware until reset/reinitialization; firmware download/upload image types can alter flash, backup, manufacturing, SBR, CPLD, PSOC, coredump, or product-specific regions; power-management requests change controller/PHY power modes; IO Unit Control operations can clear persistent mappings or remove devices; MCTP passthrough transfers are transient.

Dependencies and integration: depends on base MPI types and SGE/version definitions from neighboring MPI headers, especially `mpi2_type.h`, `mpi2.h`, `mpi2_cnfg.h`, and image/config page definitions. Integration points include the base bring-up/reset code, interrupt/reply processing, event workqueues, SCSI host/device management, sysfs/diagnostic trigger handling, and user passthrough ioctls. Comments explicitly require runtime bounds checks before indexing flexible arrays such as IR config elements, SAS topology PHY entries, and PCIe topology port entries.

Risks: every structure is an ABI with firmware, so field order, width, alignment, endian type, and flexible-array sizing are high risk. Several names are version-scoped (`MPI25`, `MPI26`) and must not be used blindly against older HBAs. Event payloads are variable length and copied from firmware; consumers must use `EventDataLength`, `NumElements`, and `NumEntries` instead of assuming the maximum shape. Feature bits are security and safety boundaries for dangerous operations such as firmware modification, diagnostic buffer ownership, MCTP passthrough, reset, and persistent device removal. The typo-like `MPI26_MCTP_MSG_CONEXT_UNUSED` is part of the local API and could be misread during maintenance.

Test signals: build coverage should include `mpt3sas` with MPI v2.0/v2.5/v2.6 code paths enabled. Runtime signals include successful IOCFacts/IOCInit/PortEnable on supported adapters, correct queue depth and RDPQ array setup, capability printouts matching hardware, event replay and event ack behavior, SAS/PCIe topology hotplug events, RAID config-change events, firmware upload/download rejection and success paths, diagnostic buffer post/release ioctls, MCTP passthrough capability checks, and reset recovery after IO Unit Control operations.
