# sources/distributed-fs/ceph-client/drivers/cpufreq/cpufreq.c

Purpose: implements the CPUFreq core: global cpufreq driver registration, per-policy lifetime, sysfs policy attributes, frequency transition notification, governor registration/switching, CPU hotplug, suspend/resume, boost handling, frequency invariance hooks, and policy refresh/update entry points used by drivers, governors, thermal cooling, scheduler code, and user space.

Important APIs and control flow: exported APIs include `disable_cpufreq()`, `get_cpu_idle_time()`, `cpufreq_generic_init()`, `cpufreq_cpu_get()/put()`, transition helpers `cpufreq_freq_transition_begin()/end()`, `cpufreq_driver_resolve_freq()`, `cpufreq_driver_target()`, notifier registration, fast-switch helpers, `cpufreq_register_governor()/unregister_governor()`, `cpufreq_update_policy()`, `cpufreq_update_limits()`, boost helpers, and `cpufreq_register_driver()/unregister_driver()`. Driver registration validates callback combinations, creates boost sysfs if supported, enables scheduler frequency invariance for target-style drivers, registers a CPU subsystem interface, initializes online CPU policies, and installs CPU hotplug callbacks. Policy online allocates or revives a `cpufreq_policy`, invokes driver `init`/`online`, validates frequency tables, creates QoS requests and sysfs files, registers stats/cooling/energy-model hooks, initializes the governor or setpolicy mode, and emits uevents. Target changes resolve the requested frequency against policy limits and frequency tables, then call driver `target`, `target_index`, optional intermediate callbacks, or fast-switch paths with transition notifications as required.

State and persistence behavior: global state includes `cpufreq_driver`, per-CPU `cpufreq_cpu_data`, active/inactive policy list, governor list, notifier chains, global cpufreq kobject, `default_governor`, suspend flag, fast-switch count, and per-CPU `cpufreq_pressure`. Per-policy state persists in kobjects, cpumasks, frequency constraints, current/min/max frequencies, governor data, stats, boost requests, transition lock/wait state, and cached frequency-table resolution. Sysfs writes persist through policy QoS requests rather than directly overwriting min/max. Hotplug preserves `last_governor` or `last_policy` across lightweight offline/online where the driver supports it.

Dependencies and integration points: depends on CPU subsystem devices, PM QoS/frequency constraints, cpumasks, kobjects/sysfs, SRCU and blocking notifier chains, scheduler frequency scale/trace hooks, `cpu_cooling`, energy model registration, cpuhp, clocks through generic drivers, and governor modules. It is the central integration point consumed by all files in this group plus external cpufreq drivers and governors.

Risks and test signals: risks include callback-combination validation gaps in third-party drivers, races around concurrent policy min/max reads during updates, governor replacement rollback failures, notifier incompatibility with fast switching, stale current-frequency detection for drivers with imprecise `get`, sysfs lifetime races if policy inactivity checks fail, and boost rollback if one policy rejects a global boost transition. Test signals include boot with a target-index driver, online/offline of all CPUs in shared and per-CPU policies, sysfs min/max/governor/setspeed writes, transition notifier ordering, stats updates, suspend/resume governor stop/start, boost sysfs toggling, frequency invariance enabled/disabled on driver register/unregister, and absence of policy kobject leaks after CPU removal.
